// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe7aCvdkYO9XpyJvJptetqAt5FcbkQkNM',
    appId: '1:995872340154:web:e838116b5cb0fdf9e5ea83',
    messagingSenderId: '995872340154',
    projectId: 'fir-e8aee',
    authDomain: 'fir-e8aee.firebaseapp.com',
    storageBucket: 'fir-e8aee.appspot.com',
    measurementId: 'G-ZRMVTM7C8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATQnxjuHDBwztSKWo948V9BlpeSvEgTCc',
    appId: '1:995872340154:android:ef6c8a561c7a7aa3e5ea83',
    messagingSenderId: '995872340154',
    projectId: 'fir-e8aee',
    storageBucket: 'fir-e8aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm3LAYdwiQwoj6GnojJs3g6COeTvV3Lw4',
    appId: '1:995872340154:ios:044e3210387c4499e5ea83',
    messagingSenderId: '995872340154',
    projectId: 'fir-e8aee',
    storageBucket: 'fir-e8aee.appspot.com',
    iosClientId: '995872340154-16d0rj9ntp5e6qt7aoad3s6reics7mdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm3LAYdwiQwoj6GnojJs3g6COeTvV3Lw4',
    appId: '1:995872340154:ios:9adf7a70266315f8e5ea83',
    messagingSenderId: '995872340154',
    projectId: 'fir-e8aee',
    storageBucket: 'fir-e8aee.appspot.com',
    iosClientId: '995872340154-empio4scn9rn6m8kdq5hsjvjkj13bml4.apps.googleusercontent.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
